export default [
    {
        id: 1,
        title: "Chicken curry",
        description: "Kale and chicken curry served on rice. Medium spice level.",
        difficulty: "Intermediate",
        time: "1 hour",
        ingredients: ["1 tbsp ginger", "2 cloves garlic","1 tbsp butter", "1 onion, diced", "rice"],
        method: ["marrinade chicken", "fry onion", "add tomatos"],
        servings: "4",
        imageURL: "https://www.foodandwine.com/thmb/8YAIANQTZnGpVWj2XgY0dYH1V4I=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/spicy-chicken-curry-FT-RECIPE0321-58f84fdf7b484e7f86894203eb7834e7.jpg",
        favorite: false
    },
    {
        id: 2,
        title: "Beef curry",
        description: "Kale and chicken curry served on rice. Medium spice level.",
        difficulty: "Hard",
        time: "1 hour",
        ingredients: ["beef", "lemon juice", "rice"],
        method: ["make sauce", "make rice", "simmer for 30 mins"],
        servings: "4",
        imageURL: "https://images.immediate.co.uk/production/volatile/sites/30/2020/08/beef-curry-711a4c1.jpg?quality=90&resize=440,400",
        favorite: false
    },
    {
        id: 3,
        title: "Spag bol",
        description: "Spaggetti bollegnasse",
        difficulty: "Easy",
        time: "30 minutes",
        ingredients: ["tomato", "carrot", "mince"],
        method: ["make pasta", "fry everything", "serve"],
        servings: "4",
        imageURL: "https://img.taste.com.au/5qlr1PkR/taste/2016/11/spaghetti-bolognese-106560-1.jpeg",
        favorite: false
    },
    {
        id: 4,
        title: "Potato salad",
        description: "Cold potato and bacon salad with creamy dressing",
        difficulty: "Intermediate",
        time: "30 minutes",
        ingredients: ["[potato", "bacon", "summer vege", "mayo"],
        method: ["cook potatoes till fork tender", "dice all vege", "make dressing"],
        servings: "4",
        imageURL: "https://twokooksinthekitchen.com/wp-content/uploads/2022/04/herbed-potato-salad-2.jpg",
        favorite: false
    },
    {
        id: 5,
        title: "Chicken curry",
        description: "Kale and chicken curry served on rice. Medium spice level.",
        difficulty: "Intermediate",
        time: "1 hour",
        ingredients: ["1 tbsp ginger", "2 cloves garlic","1 tbsp butter", "1 onion, diced", "rice"],
        method: ["marrinade chicken", "fry onion", "add tomatos"],
        servings: "4",
        imageURL: "https://www.foodandwine.com/thmb/8YAIANQTZnGpVWj2XgY0dYH1V4I=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/spicy-chicken-curry-FT-RECIPE0321-58f84fdf7b484e7f86894203eb7834e7.jpg",
        favorite: false
    },
    {
        id: 6,
        title: "Beef curry",
        description: "Kale and chicken curry served on rice. Medium spice level.",
        difficulty: "Hard",
        time: "1 hour",
        ingredients: ["beef", "lemon juice", "rice"],
        method: ["make sauce", "make rice", "simmer for 30 mins"],
        servings: "4",
        imageURL: "https://images.immediate.co.uk/production/volatile/sites/30/2020/08/beef-curry-711a4c1.jpg?quality=90&resize=440,400",
        favorite: false
    },
    {
        id: 7,
        title: "Spag bol",
        description: "Spaggetti bollegnasse",
        difficulty: "Easy",
        time: "30 minutes",
        ingredients: ["tomato", "carrot", "mince"],
        method: ["make pasta", "fry everything", "serve"],
        servings: "4",
        imageURL: "https://img.taste.com.au/5qlr1PkR/taste/2016/11/spaghetti-bolognese-106560-1.jpeg",
        favorite: false
    },
    {
        id: 8,
        title: "Potato salad",
        description: "Cold potato and bacon salad with creamy dressing",
        difficulty: "Intermediate",
        time: "30 minutes",
        ingredients: ["[potato", "bacon", "summer vege", "mayo"],
        method: ["cook potatoes till fork tender", "dice all vege", "make dressing"],
        servings: "4",
        imageURL: "https://twokooksinthekitchen.com/wp-content/uploads/2022/04/herbed-potato-salad-2.jpg",
        favorite: false
    },
    {
        id: 9,
        title: "Chicken curry",
        description: "Kale and chicken curry served on rice. Medium spice level.",
        difficulty: "Intermediate",
        time: "1 hour",
        ingredients: ["1 tbsp ginger", "2 cloves garlic","1 tbsp butter", "1 onion, diced", "rice"],
        method: ["marrinade chicken", "fry onion", "add tomatos"],
        servings: "4",
        imageURL: "https://www.foodandwine.com/thmb/8YAIANQTZnGpVWj2XgY0dYH1V4I=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/spicy-chicken-curry-FT-RECIPE0321-58f84fdf7b484e7f86894203eb7834e7.jpg",
        favorite: false
    },
    {
        id: 10,
        title: "Beef curry",
        description: "Kale and chicken curry served on rice. Medium spice level.",
        difficulty: "Hard",
        time: "1 hour",
        ingredients: ["beef", "lemon juice", "rice"],
        method: ["make sauce", "make rice", "simmer for 30 mins"],
        servings: "4",
        imageURL: "https://images.immediate.co.uk/production/volatile/sites/30/2020/08/beef-curry-711a4c1.jpg?quality=90&resize=440,400",
        favorite: false
    },
    {
        id: 11,
        title: "Spag bol",
        description: "Spaggetti bollegnasse",
        difficulty: "Easy",
        time: "30 minutes",
        ingredients: ["tomato", "carrot", "mince"],
        method: ["make pasta", "fry everything", "serve"],
        servings: "4",
        imageURL: "https://img.taste.com.au/5qlr1PkR/taste/2016/11/spaghetti-bolognese-106560-1.jpeg",
        favorite: false
    },
    {
        id: 12,
        title: "Potato salad",
        description: "Cold potato and bacon salad with creamy dressing",
        difficulty: "Intermediate",
        time: "30 minutes",
        ingredients: ["[potato", "bacon", "summer vege", "mayo"],
        method: ["cook potatoes till fork tender", "dice all vege", "make dressing"],
        servings: "4",
        imageURL: "https://twokooksinthekitchen.com/wp-content/uploads/2022/04/herbed-potato-salad-2.jpg",
        favorite: false
    },

]