export default [
    {
        id: 1,
        title: "Chicken curry",
        description: "Kale and chicken curry served on rice. Medium spice level.",
        difficulty: "Intermediate",
        time: "1 hour",
        ingredients: ["1 tbsp ginger", "2 cloves garlic","1 tbsp butter", "1 onion, diced", "rice"],
        method: ["marrinade chicken", "fry onion", "add tomatos"],
        servings: "4",
        imageURL: "https://www.foodandwine.com/thmb/8YAIANQTZnGpVWj2XgY0dYH1V4I=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/spicy-chicken-curry-FT-RECIPE0321-58f84fdf7b484e7f86894203eb7834e7.jpg",
        favourite: false,
        rating: "5", 
    },
    {
        id: 2,
        title: "Beef curry",
        description: "Kale and chicken curry served on rice. Medium spice level.",
        difficulty: "Hard",
        time: "1 hour",
        ingredients: ["beef", "lemon juice", "rice"],
        method: ["make sauce", "make rice", "simmer for 30 mins"],
        servings: "4",
        imageURL: "https://images.immediate.co.uk/production/volatile/sites/30/2020/08/beef-curry-711a4c1.jpg?quality=90&resize=440,400",
        favourite: false,
        rating: "5",
    },
    {
        id: 3,
        title: "Spaghetti bolognese",
        description: "Spaggetti bollegnasse mmmm yummy!!! So warm to eat but only yum with cheese :P Mince is on speical at new world this week hananh buy some and feeeze it. Spaggetti bollegnasse mmmm yummy!!! So warm to eat but only yum with cheese :P Mince is on speical at new world this week hananh buy some and feeeze it.",
        difficulty: "Easy",
        time: "30 minutes",
        ingredients: ["tomato", "carrot", "mince", "onion", "mixed herbs", "dash of oil", "pasta", "salt", "garlic"],
        method: ["Boil the pasta in salted water", "While pasta is cooking, fry onions on medium heat till soft", "add mince, fry till browned", "add mixed herbs, canned tomatos and garlic", "simmer for 15 minutes till the sauce has reduced", "add grated carrot, and cook for 3 more minutes", "serve wth the cooked pasta and grated cheese"],
        servings: "4",
        imageURL: "https://img.taste.com.au/5qlr1PkR/taste/2016/11/spaghetti-bolognese-106560-1.jpeg",
        favourite: true,
        rating: "4",
    },
    {
        id: 4,
        title: "Potato salad",
        description: "Cold potato and bacon salad with creamy dressing",
        difficulty: "Intermediate",
        time: "30 minutes",
        ingredients: ["[potato", "bacon", "summer vege", "mayo"],
        method: ["cook potatoes till fork tender", "dice all vege", "make dressing"],
        servings: "4",
        imageURL: "https://twokooksinthekitchen.com/wp-content/uploads/2022/04/herbed-potato-salad-2.jpg",
        favourite: false,
        rating: "3",
    },
    {
        id: 5,
        title: "Vegemite toast",
        description: "Kale and chicken curry served on rice. Medium spice level.",
        difficulty: "Intermediate",
        time: "1 hour",
        ingredients: ["1 tbsp ginger", "2 cloves garlic","1 tbsp butter", "1 onion, diced", "rice"],
        method: ["marrinade chicken", "fry onion", "add tomatos"],
        servings: "4",
        imageURL: "https://upload.wikimedia.org/wikipedia/commons/1/10/Vegemiteontoast_large.jpg",
        favourite: true,
        rating: "5",
    },
    {
        id: 6,
        title: "Corn fritter",
        description: "Kale and chicken curry served on rice. Medium spice level.",
        difficulty: "Hard",
        time: "1 hour",
        ingredients: ["beef", "lemon juice", "rice"],
        method: ["make sauce", "make rice", "simmer for 30 mins"],
        servings: "4",
        imageURL: "https://cookingwithayeh.com/wp-content/uploads/2021/02/Zucchini-Corn-Fritters-0.jpg",
        favourite: false,
        rating: "4",
    },
    {
        id: 7,
        title: "Dumplings",
        description: "Spaggetti bollegnasse",
        difficulty: "Easy",
        time: "30 minutes",
        ingredients: ["tomato", "carrot", "mince"],
        method: ["make pasta", "fry everything", "serve"],
        servings: "4",
        imageURL: "https://cdn.apartmenttherapy.info/image/upload/f_jpg,q_auto:eco,c_fill,g_auto,w_1500,ar_1:1/k%2Farchive%2F8f8b6fc612a03855c59f0cca1fffad07ce6858ca",
        favourite: true,
        rating: "2",
    },
    {
        id: 8,
        title: "Burgers",
        description: "Cold potato and bacon salad with creamy dressing",
        difficulty: "Intermediate",
        time: "30 minutes",
        ingredients: ["[potato", "bacon", "summer vege", "mayo"],
        method: ["cook potatoes till fork tender", "dice all vege", "make dressing"],
        servings: "4",
        imageURL: "https://images.immediate.co.uk/production/volatile/sites/30/2013/05/Cheeseburger-3d7c922.jpg",
        favourite: true,
        rating: "3",
    },
    {
        id: 9,
        title: "Sausages",
        description: "Kale and chicken curry served on rice. Medium spice level.",
        difficulty: "Intermediate",
        time: "1 hour",
        ingredients: ["1 tbsp ginger", "2 cloves garlic","1 tbsp butter", "1 onion, diced", "rice"],
        method: ["marrinade chicken", "fry onion", "add tomatos"],
        servings: "4",
        imageURL: "https://cdn.shopify.com/s/files/1/0277/2818/3436/products/446477620_1000x.jpg?v=1584845895",
        favourite: false,
        rating: "1",
    },
    {
        id: 10,
        title: "Enchiladas",
        description: "Kale and chicken curry served on rice. Medium spice level.",
        difficulty: "Hard",
        time: "1 hour",
        ingredients: ["beef", "lemon juice", "rice"],
        method: ["make sauce", "make rice", "simmer for 30 mins"],
        servings: "4",
        imageURL: "https://food.fnr.sndimg.com/content/dam/images/food/fullset/2012/10/1/0/WU0308H_simple-perfect-enchiladas_s4x3.jpg.rend.hgtvcom.616.462.suffix/1382541970364.jpeg",
        favourite: false,
        rating: "2",
    },
    {
        id: 11,
        title: "Tacos",
        description: "Spaggetti bollegnasse",
        difficulty: "Easy",
        time: "30 minutes",
        ingredients: ["tomato", "carrot", "mince"],
        method: ["make pasta", "fry everything", "serve"],
        servings: "4",
        imageURL: "https://img.taste.com.au/R_dRdL7V/taste/2022/09/healthy-tacos-recipe-181113-1.jpg",
        favourite: true,
        rating: "3",
    },
    {
        id: 12,
        title: "Hot dogs",
        description: "Cold potato and bacon salad with creamy dressing",
        difficulty: "Intermediate",
        time: "30 minutes",
        ingredients: ["[potato", "bacon", "summer vege", "mayo"],
        method: ["cook potatoes till fork tender", "dice all vege", "make dressing"],
        servings: "4",
        imageURL: "https://images.immediate.co.uk/production/volatile/sites/30/2020/08/processed-food700-350-e6d0f0f.jpg",
        favourite: false,
        rating: "4",
    },
    {
        id: 13,
        title: "Poutine",
        description: "Cold potato and bacon salad with creamy dressing",
        difficulty: "Intermediate",
        time: "30 minutes",
        ingredients: ["[potato", "bacon", "summer vege", "mayo"],
        method: ["cook potatoes till fork tender", "dice all vege", "make dressing"],
        servings: "4",
        imageURL: "https://www.bhg.com/thmb/L5QEf1UXOAXXY_uaMzjnlWexk3Y=/1500x0/filters:no_upscale():strip_icc()/quick-poutine-BBOQQT52qRM8_P2JsdQxXI-2336ec1ff4744ee89333a3da76fd7ae3.jpg",
        favourite: false,
        rating: "1",
    },

]